### ISSUE TITLE
command not found: cmake will installing

### ISSUE THREAD

**Issue by dorshay6** [dfellis/h3-node#23]
`command not found: cmake` is happing while installing.

**Comment by dfellis** [comment]
Right. I intend to eventually move to something like [prebuildify](https://github.com/prebuild/prebuildify) along with some CI system to auto-create an array of NAPI binaries for users, but I haven't quite figured it out locally, yet (and regular work has gotten in the way), so right now you have to have the build tools for both Node.js and H3 installed, which includes `cmake`, [as stated in the first sentence of the install section of the README](https://github.com/dfellis/h3-node#install).

I am open to PRs to use prebuildify or similar to remove this requirement for users of the library. :)

But in the meantime, please install `cmake` on your machine so [the H3 C code](https://github.com/uber/h3) can be compiled.

**Comment by dfellis** [comment]
Alright, starting with v3.4.6, you can install for node v11 and not need any build tools. For earlier version you still need the build tools, but I hope to expand the prebuilt artifacts soon.

**Comment by dfellis** [comment]
There are now builds for Node 8, 10, and 11 for Windows, Mac, and Linux OSes. Going to call this solved.

**Comment by dorshay6** [comment]
WOW Great!
