### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Slawlight** [dfellis/h3-node#29]
why did I have this error: require is not defined at Object.eval?
<img width="540" alt="屏幕快照 2019-03-22 上午10 42 10" src="https://user-images.githubusercontent.com/18410535/54797527-75afca80-4c8f-11e9-91d8-c8bfb0b338da.png">

**Comment by dfellis** [comment]
h3-node is meant for higher-performance H3 usage in Node.js, so it uses bindings to native C code to work and doesn't work in the browser.

For the Web, you need to use the emscripten-transpiled [h3-js](https://github.com/uber/h3-js) instead.

h3-js will also work in Node, but will be anywhere from a little bit slower to half the speed of this library, depending on the operation.

**Comment by Slawlight** [comment]
Thanks.
