### ISSUE TITLE
Failed at the h3-node@3.6.7 install script.

### ISSUE THREAD

**Issue by hkrhasan** [dfellis/h3-node#37]
`npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! h3-node@3.6.7 install: `bash -c "if node-gyp-build-test; then node-gyp-build; else npm run prebuild && node-gyp-build; fi"`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the h3-node@3.6.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ptipl\AppData\Roaming\npm-cache\_logs\2021-03-02T10_19_35_292Z-debug.log`

**Comment by hkrhasan** [comment]
> 
> 
> `npm ERR! code ELIFECYCLE npm ERR! errno 2 npm ERR! h3-node@3.6.7 install: `bash -c "if node-gyp-build-test; then node-gyp-build; else npm run prebuild && node-gyp-build; fi"`
> npm ERR! Exit status 2
> npm ERR!
> npm ERR! Failed at the h3-node@3.6.7 install script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR! C:\Users\ptipl\AppData\Roaming\npm-cache_logs\2021-03-02T10_19_35_292Z-debug.log`



**how can i solve this problem**

**Comment by dfellis** [comment]
Two things:

1. Can you attach the complete `C:\Users\ptipl\AppData\Roaming\npm-cache_logs\2021-03-02T10_19_35_292Z-debug.log` file contents in here? I don't know what that actually failed on.
2. I can see by that path that you're using Windows. `node-gyp` supposedly supports Windows, and I do have Github Actions set up to test Windows, I've noticed when using a Windows VM that there's often a lot of developer tooling you need to install beforehand that no one tells you about, so getting this to work on your computer may take multiple iterations back and forth to see what's necessary that's missing.

**Comment by dfellis** [comment]
@hkrhasan it's been about 2 weeks. I'm gonna wait one more week for an answer to those two questions above, and if still unanswered, I will close out the issue. Sorry you ran into this, though!
